/**
 * Attribution / credits — generated catalog reader.
 *
 * `data/credits.json` is generated by `npm run credits:build`
 * (scripts/credits-build.mjs, from scripts/lib/credits-registry.json) — never
 * hand-edit it. This module normalizes it the way lib/releaseNotes.js
 * normalizes data/release-notes.json: ships in the bundle so Settings → Credits
 * reads with no signal, one small seam the UI and tests both go through.
 */

import catalog from '../data/credits.json' with { type: 'json' };

/**
 * @typedef {{id:string,name:string,license:string,url:string,attribution:string,detail?:string,credit?:string,note?:string,placement?:string}} CreditItem
 * @typedef {{role:string,label:string,items:CreditItem[]}} CreditGroup
 */

/**
 * @param {{groups?: CreditGroup[]}} [source]
 * @returns {CreditGroup[]}
 */
export function creditGroups(source = catalog) {
  return Array.isArray(source?.groups) ? source.groups : [];
}

/**
 * @param {{overarchingNote?: string}} [source]
 * @returns {string}
 */
export function creditsOverarchingNote(source = catalog) {
  return source?.overarchingNote || '';
}

/**
 * The registry row an on-map or placed-link notice should point back to, so
 * a UI element that renders a credit line stays in sync with the generated
 * catalog instead of hardcoding text a rebuild could drift away from.
 * @param {string} id
 * @param {{groups?: CreditGroup[]}} [source]
 * @returns {CreditItem | null}
 */
export function creditItem(id, source = catalog) {
  for (const group of creditGroups(source)) {
    const hit = group.items.find((item) => item.id === id);
    if (hit) return hit;
  }
  return null;
}

/** The persistent on-map ODbL notice's text — sourced from the `openstreetmap`
 * registry row's `credit` line (scripts/lib/credits-registry.json) rather than
 * a second hardcoded copy, so editing the registry can't silently desync the
 * two places that string appears. */
export function osmNoticeText(source = catalog) {
  return creditItem('openstreetmap', source)?.credit || '© OpenStreetMap contributors';
}
