/**
 * Universal Venue Builder — external dependency matrix (code registry).
 *
 * Evaluates open-source projects against capability, license, integration cost,
 * and overlap with scripts/ and lib/ in this repo. See also:
 *   docs/universal-venue-builder-dependency-matrix.md
 *
 * adopt modes:
 *   adopt   — use as primary implementation in a service
 *   wrap    — CLI/container adapter, no fork (preferred)
 *   fork    — only if upstream cannot be wrapped
 *   replace — supersedes something we built
 *   evaluate — head-to-head bake-off (e.g. Valhalla vs GraphHopper)
 *   defer   — Phase 2+; weights reserved in evidence engine
 *   reject  — conflicts with offline-first runtime constraints
 */

import { defineAdapter } from './types.mjs';

const ENTRIES = [
  // —— AI orchestration ——
  {
    id: 'venue-build-orchestrator',
    name: 'Build agent orchestrator (this repo)',
    repo: 'six-flags-sa',
    url: 'scripts/venue-build-agent.mjs',
    capability: 'LLM-coordinated QA, research, GIS, vision, validation agents',
    role: 'BUILD_ORCHESTRATOR',
    stage: 'orchestration',
    license: 'MIT',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'low',
    overlap: 'Node orchestrator; LangGraph pattern without Python embed',
    notes: 'npm run venues:build-agent -- <id> [--ai] [--apply]',
  },
  {
    id: 'langgraph',
    name: 'LangGraph',
    repo: 'langchain-ai/langgraph',
    url: 'https://github.com/langchain-ai/langgraph',
    capability: 'Stateful multi-agent workflows for venue build pipelines',
    role: 'BUILD_ORCHESTRATOR_OPTION',
    stage: 'orchestration',
    license: 'MIT',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['python'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'venue-build-agent.mjs implements the same flow in Node',
    notes: 'Optional external orchestrator; not required.',
  },
  {
    id: 'langchain',
    name: 'LangChain',
    repo: 'langchain-ai/langchain',
    url: 'https://github.com/langchain-ai/langchain',
    capability: 'LLM tools, retrievers, model integrations',
    role: 'LLM_TOOL_LAYER',
    stage: 'orchestration',
    license: 'MIT',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['python', 'javascript'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'venue-llm.mjs optional OpenAI-compatible chat only',
    notes: 'Under LangGraph, not as the architecture root.',
  },
  {
    id: 'playwright',
    name: 'Playwright',
    repo: 'microsoft/playwright',
    url: 'https://github.com/microsoft/playwright',
    capability: 'Browser automation for official sites, maps, accessibility pages',
    role: 'WEB_RESEARCH_AGENT',
    stage: 'research',
    license: 'Apache-2.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript', 'python'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['official_site', 'official_map'],
    integration: 'low',
    overlap: 'devDependency + test/browser.mjs; venue-official-site.mjs uses fetch+regex',
    notes: 'Extend research agent beyond regex HTML parsing. Not on rebuild hot path.',
  },

  // —— Theme park operational data ——
  {
    id: 'themeparks-cubehouse',
    name: 'cubehouse/themeparks',
    repo: 'cubehouse/themeparks',
    url: 'https://github.com/cubehouse/themeparks',
    capability: 'Unofficial park metadata, wait times, hours (legacy implementation)',
    role: 'VENUE_DATA_ADAPTER_LEGACY',
    stage: 'venue_data',
    license: 'MIT',
    adopt: 'evaluate',
    maturity: 'beta',
    maintenance: 2,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['parks_api'],
    integration: 'medium',
    overlap: 'No external ride APIs wired',
    notes: 'Study acquisition model; successor ParksAPI preferred for active maintenance.',
  },
  {
    id: 'parks-api',
    name: 'ParksAPI (themeparks successor)',
    repo: 'cubehouse/ParksAPI',
    url: 'https://github.com/cubehouse/ParksAPI',
    capability: 'Park identification, attraction inventories, hours, wait-time concepts',
    role: 'VENUE_DATA_ADAPTER',
    stage: 'venue_data',
    license: 'MIT',
    adopt: 'wrap',
    maturity: 'beta',
    maintenance: 4,
    languages: ['javascript', 'typescript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['parks_api'],
    integration: 'medium',
    overlap: 'Heights from official sites; no live ops feed in client',
    notes: 'Metadata + ops concepts into sidecar; client stays offline JSON.',
  },

  // —— OpenStreetMap ecosystem ——
  {
    id: 'osm',
    name: 'OpenStreetMap',
    repo: 'openstreetmap/openstreetmap-website',
    url: 'https://www.openstreetmap.org',
    capability: 'Base venue skeleton: paths, buildings, attractions, amenities',
    role: 'GEO_FOUNDATION',
    stage: 'geo',
    license: 'ODbL (data)',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['various'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['osm_entrance', 'osm_named_queue', 'osm_queue_name'],
    integration: 'low',
    overlap: 'Core: build-venue.mjs Overpass + osm-tags.mjs',
    notes: 'Already the geospatial foundation.',
  },
  {
    id: 'overpass-api',
    name: 'Overpass API',
    repo: 'drolbr/Overpass-API',
    url: 'https://github.com/drolbr/Overpass-API',
    capability: 'Structured OSM queries over bounding boxes',
    role: 'OSM_QUERY',
    stage: 'geo',
    license: 'AGPL-3.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['osm_entrance', 'osm_named_queue'],
    integration: 'low',
    overlap: 'Mirrors in build-venue.mjs',
    notes: 'Optional local Overpass for air-gapped builds.',
  },
  {
    id: 'osmium',
    name: 'Osmium',
    repo: 'osmcode/libosmium',
    url: 'https://github.com/osmcode/libosmium',
    capability: 'Fast OSM PBF processing, extracts, merges',
    role: 'OSM_TOOLKIT',
    stage: 'geo',
    license: 'BSD-2-Clause',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'Live Overpass queries today; no local PBF pipeline',
    notes: 'Regional extracts for offline routing graph prep.',
  },
  {
    id: 'nominatim',
    name: 'Nominatim',
    repo: 'osm-search/Nominatim',
    url: 'https://github.com/osm-search/Nominatim',
    capability: 'Place resolution for --place builds',
    role: 'GEO_PLACE_LOOKUP',
    stage: 'geo',
    license: 'GPL-2.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['python', 'c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'low',
    overlap: 'Public Nominatim in build-venue.mjs',
    notes: 'Self-hosted option for reproducible place resolution.',
  },

  // —— Routing engines ——
  {
    id: 'graphhopper',
    name: 'GraphHopper',
    repo: 'graphhopper/graphhopper',
    url: 'https://github.com/graphhopper/graphhopper',
    capability: 'OSM routing, isochrones, snap-to-network',
    role: 'VENUE_ROUTING_ENGINE_CANDIDATE',
    stage: 'geo',
    license: 'Apache-2.0',
    adopt: 'evaluate',
    maturity: 'production',
    maintenance: 4,
    languages: ['java'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'high',
    overlap: 'Client A* in lib/routing.js (~1.8ms); park-intelligence-review rejects server routing',
    notes: 'Theme parks need pedestrian venue graphs, not road networks. Bake-off with Valhalla.',
  },
  {
    id: 'valhalla',
    name: 'Valhalla',
    repo: 'valhalla/valhalla',
    url: 'https://github.com/valhalla/valhalla',
    capability: 'Pedestrian/multimodal routing, dynamic costing, regional tiles',
    role: 'VENUE_ROUTING_ENGINE_CANDIDATE',
    stage: 'geo',
    license: 'MIT',
    adopt: 'evaluate',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'high',
    overlap: 'Rejected for phone runtime; could assist builder path validation only',
    notes: 'Builder-side "minimize walking" QA, not phone dependency.',
  },

  // —— Map rendering & tiles ——
  {
    id: 'maplibre-gl-js',
    name: 'MapLibre GL JS',
    repo: 'maplibre/maplibre-gl-js',
    url: 'https://github.com/maplibre/maplibre-gl-js',
    capability: 'WebGL vector-tile map renderer with custom styling',
    role: 'MAP_RENDERER_OPTION',
    stage: 'runtime_map',
    license: 'BSD-2-Clause',
    adopt: 'evaluate',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript', 'typescript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'high',
    overlap: 'Custom SVG ParkMap.jsx — offline, dependency-free',
    notes: 'Future layer if vector tiles justify bundle size. Not required for MVP.',
  },
  {
    id: 'tippecanoe',
    name: 'Tippecanoe',
    repo: 'felt/tippecanoe',
    url: 'https://github.com/felt/tippecanoe',
    capability: 'GeoJSON → vector tiles with zoom-aware detail',
    role: 'TILE_PIPELINE',
    stage: 'tiles',
    license: 'BSD-2-Clause',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'Full geometry in map.json today',
    notes: 'Venue Builder → GeoJSON → Tippecanoe → tiles → optional MapLibre.',
  },

  // —— Street imagery & SfM ——
  {
    id: 'mapillary-tools',
    name: 'Mapillary Tools',
    repo: 'mapillary/mapillary_tools',
    url: 'https://github.com/mapillary/mapillary_tools',
    capability: 'Geotagged imagery/video processing, GPX alignment',
    role: 'GROUND_IMAGERY_INGEST',
    stage: 'vision',
    license: 'BSD-2-Clause',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 3,
    languages: ['python'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['mapillary', 'video'],
    integration: 'medium',
    overlap:
      'Manual aerial survey for Big Kahunas only. Shares the mapillary_tools CLI with the mapillary-api row (image API vs. this row\'s video_process implementation in lib/adapters/mapillary-video.mjs).',
    notes:
      'Queue entrance candidates from street-level sequences + API metadata. Requires ctx.videoPath for the video path; not in DEFAULT_EXTERNAL_ADAPTERS since a walkthrough video must be manually supplied.',
  },
  {
    id: 'mapillary-js',
    name: 'Mapillary JS',
    repo: 'mapillary/mapillary-js',
    url: 'https://github.com/mapillary/mapillary-js',
    capability: 'Interactive street-level WebGL viewer',
    role: 'VALIDATION_UI_IMAGERY',
    stage: 'vision',
    license: 'MIT',
    adopt: 'defer',
    maturity: 'production',
    maintenance: 3,
    languages: ['javascript', 'typescript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['mapillary'],
    integration: 'medium',
    overlap: 'Human validation UI identified as high-leverage gap',
    notes: 'Pairs with validation UI for evidence review.',
  },
  {
    id: 'opensfm',
    name: 'OpenSfM',
    repo: 'mapillary/OpenSfM',
    url: 'https://github.com/mapillary/OpenSfM',
    capability: 'Structure-from-motion 3D reconstruction from photos',
    role: 'ADVANCED_GEOMETRY',
    stage: 'vision',
    license: 'BSD-2-Clause',
    adopt: 'defer',
    maturity: 'beta',
    maintenance: 3,
    languages: ['python'],
    docker: true,
    gpu: true,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['aerial', 'cv_segmentation'],
    integration: 'high',
    overlap: 'Phase 3 — not MVP',
    notes: 'Buildings, queues, stations from multi-view photos.',
  },

  // —— Computer vision ——
  {
    id: 'ultralytics-yolo',
    name: 'Ultralytics YOLO',
    repo: 'ultralytics/ultralytics',
    url: 'https://github.com/ultralytics/ultralytics',
    capability: 'Detection, tracking, segmentation for venue features',
    role: 'VISION_DETECTOR',
    stage: 'vision',
    license: 'AGPL-3.0',
    adopt: 'reject',
    maturity: 'production',
    maintenance: 5,
    languages: ['python'],
    docker: true,
    gpu: true,
    offline: true,
    commercial_ok: false,
    evidence_sources: [],
    integration: 'high',
    overlap: 'Rejected — AGPL; use SAM 2 or external CV service only',
    notes: 'Not wrapped by agents. See docs/THIRD_PARTY_LICENSES.md.',
  },
  {
    id: 'sam2',
    name: 'SAM 2',
    repo: 'facebookresearch/sam2',
    url: 'https://github.com/facebookresearch/sam2',
    capability: 'Promptable image/video segmentation → polygons',
    role: 'VISION_SEGMENTER',
    stage: 'vision',
    license: 'Apache-2.0',
    adopt: 'defer',
    maturity: 'beta',
    maintenance: 4,
    languages: ['python'],
    docker: true,
    gpu: true,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['cv_segmentation'],
    integration: 'high',
    overlap: 'Same deferral as YOLO',
    notes: 'Segment queue structures for georeferenced polygons.',
  },
  {
    id: 'esa-worldcover',
    name: 'ESA WorldCover',
    repo: 'ESA-WorldCover/esa-worldcover-datasets',
    url: 'https://esa-worldcover.org/en/data-access',
    capability: 'Global 10 m land-cover classification (aerial evidence + Display land-tone input)',
    role: 'LAND_COVER_CLASSIFIER',
    stage: 'vision',
    license: 'CC BY 4.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['n/a'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['aerial'],
    integration: 'low',
    overlap:
      'lib/adapters/esa-worldcover.mjs reads public esa-worldcover S3 COGs via HTTP byte ranges (geotiff npm package) — no full-tile download, no API key, no rate limit.',
    notes:
      'Cross-checks the two highest-weight entrance-evidence sources (park map=5, aerial=4): does the classified land under a claim match what it implies? Also the cheapest land-tone base layer for PR #471 Display (see registry\'s poly-haven row) — same raster, two consumers, one adapter.',
  },

  // —— Display-layer materials (PR #471 PBR pipeline) — never evidence_sources ——
  {
    id: 'poly-haven',
    name: 'Poly Haven',
    repo: 'n/a (asset library, not source-hosted)',
    url: 'https://polyhaven.com/textures',
    capability: 'CC0 PBR material sets (asphalt, roofing, foliage) for the Display pipeline',
    role: 'PBR_MATERIAL_LIBRARY',
    stage: 'display',
    license: 'CC0',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['n/a'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'low',
    overlap: 'PR #471 material pipeline / visual.json land tones — Display, not Truth',
    notes:
      'lib/adapters/poly-haven.mjs writes a committed data/display/materials.json ledger (license + provenance + file URLs); texture bytes fetch at build time and are never committed. No water category — Poly Haven has no static PBR water texture (checked directly against its API); water stays a documented gap, not a fabricated slug.',
  },

  // —— Open-source research adapters (builder-side) ——
  {
    id: 'queue-times',
    name: 'Queue-Times.com',
    repo: 'Queue-Times/queue-times',
    url: 'https://queue-times.com',
    capability: 'Live wait times cross-check for attraction inventories',
    role: 'VENUE_DATA_ADAPTER',
    stage: 'venue_data',
    license: 'MIT',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['ruby'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['queue_times'],
    integration: 'low',
    overlap: 'ParksAPI inventory; wait times for QA only',
    notes: 'Cached to data/venues/<id>.queue-times-cache.json. Not shipped to client.',
  },
  {
    id: 'ropedrop',
    name: 'RopeDrop open data',
    repo: 'RopeDropNews/theme-park-open-data',
    url: 'https://github.com/RopeDropNews/theme-park-open-data',
    capability: 'Disney/Universal wait-time and reliability research data',
    role: 'VENUE_DATA_ADAPTER',
    stage: 'venue_data',
    license: 'CC BY 4.0',
    adopt: 'wrap',
    maturity: 'beta',
    maintenance: 3,
    languages: ['json'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['ropedrop'],
    integration: 'low',
    overlap: 'Disney/Universal venues only',
    notes: 'Extend ROPEDROP_SLUGS when Disney parks ship.',
  },
  {
    id: 'wikidata',
    name: 'Wikidata',
    repo: 'wikidata/wikidata',
    url: 'https://www.wikidata.org',
    capability: 'Entity resolution, aliases, operator, coordinates',
    role: 'VENUE_METADATA',
    stage: 'research',
    license: 'CC0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['various'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['wikidata'],
    integration: 'low',
    overlap: 'Official site names; venue-level metadata only',
    notes: 'Q-ids in lib/park-slug-map.mjs for shipped parks.',
  },
  {
    id: 'rcdb',
    name: 'RCDB cross-check',
    repo: 'community/rcdb-api',
    url: 'https://rcdb.com',
    capability: 'Coaster height/speed stats for comparison',
    role: 'VENUE_DATA_ADAPTER',
    stage: 'venue_data',
    license: 'unofficial',
    adopt: 'wrap',
    maturity: 'beta',
    maintenance: 2,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['rcdb'],
    integration: 'low',
    overlap: 'Height sidecar from official sites',
    notes: 'Compare-only; never overrides official height rules.',
  },
  {
    id: 'accessibility-cloud',
    name: 'Accessibility Cloud',
    repo: 'sozialhelden/accessibility-cloud',
    url: 'https://accessibility.cloud',
    capability: 'Wheelchair accessibility ratings near venue',
    role: 'ACCESSIBILITY_RESEARCH',
    stage: 'research',
    license: 'varies',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 3,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['accessibility_cloud'],
    integration: 'low',
    overlap: 'OSM wheelchair tags',
    notes: 'Requires ACCESSIBILITY_CLOUD_TOKEN.',
  },
  {
    id: 'project-sidewalk',
    name: 'Project Sidewalk',
    repo: 'ProjectSidewalk/SidewalkWebpage',
    url: 'https://projectsidewalk.org',
    capability: 'Sidewalk accessibility labels in bbox',
    role: 'ACCESSIBILITY_RESEARCH',
    stage: 'research',
    license: 'open research',
    adopt: 'wrap',
    maturity: 'beta',
    maintenance: 3,
    languages: ['scala', 'javascript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['sidewalk_labels'],
    integration: 'low',
    overlap: 'Path network from OSM',
    notes: 'US cities with Project Sidewalk coverage only.',
  },
  {
    id: 'guest-traces',
    name: 'Parkbound guest movement traces',
    repo: 'six-flags-sa',
    url: 'apps/party-tracker/app/api/contributions/traces',
    capability: 'Opt-in anonymised GPS LineStrings + entrance/exit/amenity ground-truth Points',
    role: 'PATH_GEOMETRY_RESEARCH',
    stage: 'research',
    license: 'guest opt-in',
    adopt: 'adopt',
    maturity: 'beta',
    maintenance: 4,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['guest_trace'],
    integration: 'low',
    overlap: 'Complements OSM footways and entrance evidence; Strava-like heatmap + sightings inside the fence',
    notes:
      'Phones upload via /api/contributions/traces; cache as data/venues/<id>.guest-traces-cache.json. Path + queue_entrance/ride_exit/park_entrance claims. Never auto-writes public/venues.',
  },
  {
    id: 'open-meteo',
    name: 'Open-Meteo',
    repo: 'open-meteo/open-meteo',
    url: 'https://open-meteo.com',
    capability: 'Weather forecast at venue center for build context',
    role: 'CONTEXT_ADAPTER',
    stage: 'research',
    license: 'CC BY 4.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['typescript'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['open_meteo'],
    integration: 'low',
    overlap: 'None in client',
    notes: 'Builder context only; not fused into POI geometry.',
  },
  {
    id: 'openhistoricalmap',
    name: 'OpenHistoricalMap',
    repo: 'OpenHistoricalMap',
    url: 'https://openhistoricalmap.org',
    capability: 'Historic features inside venue bounds',
    role: 'GEO_RESEARCH',
    stage: 'geo',
    license: 'ODbL',
    adopt: 'wrap',
    maturity: 'beta',
    maintenance: 3,
    languages: ['various'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['openhistoricalmap'],
    integration: 'low',
    overlap: 'Current OSM geometry',
    notes: 'Overpass on openhistoricalmap.org.',
  },
  {
    id: 'mapillary-api',
    name: 'Mapillary API',
    repo: 'mapillary/mapillary_tools',
    url: 'https://www.mapillary.com',
    capability: 'Street-level imagery metadata near venue',
    role: 'GROUND_IMAGERY_INGEST',
    stage: 'vision',
    license: 'CC BY-SA',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 3,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['mapillary'],
    integration: 'low',
    overlap: 'mapillary-tools CLI row in registry',
    notes: 'Requires MAPILLARY_TOKEN.',
  },
  {
    id: 'openrouteservice',
    name: 'OpenRouteService',
    repo: 'GIScience/openrouteservice',
    url: 'https://openrouteservice.org',
    capability: 'Builder-side foot route QA against in-app graph',
    role: 'ROUTING_QA',
    stage: 'geo',
    license: 'ORS terms',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['java'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'low',
    overlap: 'Client A* routing; ORS for validation only',
    notes: 'Requires ORS_API_KEY.',
  },

  // —— Already in repo (reference rows) ——
  {
    id: 'venue-evidence-engine',
    name: 'Evidence fusion (this repo)',
    repo: 'six-flags-sa',
    url: 'scripts/lib/evidence.mjs',
    capability: 'Source-weighted fusion, publish bands, dissent reporting',
    role: 'EVIDENCE_ENGINE',
    stage: 'research',
    license: 'project',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: Object.keys({
      official_map: 1,
      official_site: 1,
      osm_entrance: 1,
      osm_named_queue: 1,
      aerial: 1,
      mapillary: 1,
      parks_api: 1,
      cv_detection: 1,
      cv_segmentation: 1,
      guest_photo: 1,
      guest_trace: 1,
      video: 1,
      traced: 1,
      geometry: 1,
    }),
    integration: 'low',
    overlap: 'Core — ahead of external proposals per park-intelligence-review',
    notes: 'Validated coordinates publish to pois.json; raw evidence stays in sidecar.',
  },
  {
    id: 'client-routing',
    name: 'Client path graph (this repo)',
    repo: 'six-flags-sa',
    url: 'lib/routing.js',
    capability: 'Offline A* on OSM path layer',
    role: 'PHONE_ROUTING',
    stage: 'geo',
    license: 'project',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'low',
    overlap: '1.8ms/query; Valhalla rejected for runtime',
    notes: 'Keep unless vector routing proves necessary on phone.',
  },
];

export const ADAPTER_REGISTRY = ENTRIES.map((e) => defineAdapter(e));

/**
 * Display feeds how the ground looks; Truth feeds evidence.mjs. A `display`
 * stage row that also carried `evidence_sources` would blur that boundary
 * silently — enforced here (not just documented) so a new Display adapter
 * can't cross it by accident.
 */
const displayStageLeak = ADAPTER_REGISTRY.find((a) => a.stage === 'display' && a.evidence_sources.length > 0);
if (displayStageLeak) {
  throw new Error(
    `adapter '${displayStageLeak.id}' is stage:'display' but declares evidence_sources — Display adapters must never feed evidence.mjs`,
  );
}

export function getAdapter(id) {
  return ADAPTER_REGISTRY.find((a) => a.id === id) || null;
}

export function adaptersByStage(stage) {
  return ADAPTER_REGISTRY.filter((a) => a.stage === stage);
}

export function adaptersByAdopt(mode) {
  return ADAPTER_REGISTRY.filter((a) => a.adopt === mode);
}

export function registrySummary() {
  const byAdopt = {};
  const byStage = {};
  for (const a of ADAPTER_REGISTRY) {
    byAdopt[a.adopt] = (byAdopt[a.adopt] || 0) + 1;
    byStage[a.stage] = (byStage[a.stage] || 0) + 1;
  }
  return {
    total: ADAPTER_REGISTRY.length,
    byAdopt,
    byStage,
  };
}
