/* Generated by scripts/build-venue.mjs — do not edit by hand.
 *
 * Static imports of every venue's POI list, for the server-side routes.
 * The browser does not use this: it fetches /venues/<id>.pois.json so that
 * a new venue is a new file rather than a new deployment.
 *
 * Rebuild with: npm run venues:reindex
 */

import manifest from '@/public/venues/manifest.json';
import pois_cedar_point from '@/public/venues/cedar-point.pois.json';
import pois_kings_island from '@/public/venues/kings-island.pois.json';
import pois_six_flags_fiesta_texas from '@/public/venues/six-flags-fiesta-texas.pois.json';

export const MANIFEST = manifest;
export const VENUES = manifest.venues;
export const DEFAULT_VENUE_ID = "kings-island";

export const POIS_BY_VENUE = {
  "cedar-point": pois_cedar_point,
  "kings-island": pois_kings_island,
  "six-flags-fiesta-texas": pois_six_flags_fiesta_texas,
};

export const venueById = (id) => VENUES.find((v) => v.id === id) || null;
