/* Where a venue lives on disk, and how the app finds out about it.
 *
 * One venue is two files plus a manifest row:
 *
 *   public/venues/<id>.map.json    the drawn geometry, fetched by the browser
 *   public/venues/<id>.pois.json   the places, fetched by the browser
 *   public/venues/manifest.json    every venue's name, centre and bounds
 *
 * They sit under public/ rather than being imported at build time because that
 * is what makes a venue swappable without a rebuild: the client fetches the one
 * it needs, the service worker caches it, and a phone that has been to two
 * parks holds both. lib/venueIndex.js is generated alongside them so the server
 * routes — which cannot fetch their own static files on every host — still get
 * the POI lists through the bundler.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

export const ROOT = fileURLToPath(new URL('../../', import.meta.url));
export const VENUE_DIR = path.join(ROOT, 'public', 'venues');
export const OVERRIDE_DIR = path.join(ROOT, 'data', 'venues');
export const INDEX_FILE = path.join(ROOT, 'lib', 'venueIndex.js');
export const MANIFEST_FILE = path.join(VENUE_DIR, 'manifest.json');

export const slugify = (s) =>
  String(s)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

export function readJson(file, fallback = null) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    return fallback;
  }
}

const writeJson = (file, value, pretty) => {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, pretty ? `${JSON.stringify(value, null, 2)}\n` : JSON.stringify(value));
};

export function writeVenue({ meta, map, pois }) {
  const id = meta.id;
  // The map file is the big one and nobody reads it by hand, so it goes out
  // minified. The POI list is small, gets edited when a name is wrong, and is
  // worth a readable diff.
  writeJson(path.join(VENUE_DIR, `${id}.map.json`), { meta, ...map }, false);
  writeJson(path.join(VENUE_DIR, `${id}.pois.json`), pois, true);
  return {
    map: path.join(VENUE_DIR, `${id}.map.json`),
    pois: path.join(VENUE_DIR, `${id}.pois.json`),
  };
}

/**
 * Rebuild the manifest and the generated index from whatever venue files are on
 * disk, so adding or deleting a venue is a matter of the files themselves.
 * `preferredDefault` only wins if that venue actually exists.
 */
export function reindex({ preferredDefault } = {}) {
  mkdirSync(VENUE_DIR, { recursive: true });
  const ids = readdirSync(VENUE_DIR)
    .filter((f) => f.endsWith('.map.json'))
    .map((f) => f.slice(0, -'.map.json'.length))
    .sort();

  const venues = [];
  for (const id of ids) {
    const map = readJson(path.join(VENUE_DIR, `${id}.map.json`));
    const pois = readJson(path.join(VENUE_DIR, `${id}.pois.json`), []);
    if (!map?.meta) {
      console.warn(`  ! ${id}.map.json has no meta block — skipped`);
      continue;
    }
    venues.push({
      ...map.meta,
      map: `/venues/${id}.map.json`,
      pois: `/venues/${id}.pois.json`,
      counts: {
        pois: pois.length,
        rides: pois.filter((p) => p.c === 'coaster' || p.c === 'ride').length,
        heights: pois.filter((p) => p.h).length,
      },
    });
  }

  const existing = readJson(MANIFEST_FILE, {});
  const wanted = preferredDefault || existing.default;
  const fallback = venues[0]?.id ?? null;
  const manifest = {
    version: 1,
    default: venues.some((v) => v.id === wanted) ? wanted : fallback,
    venues,
  };
  writeJson(MANIFEST_FILE, manifest, true);
  writeIndex(manifest);
  return manifest;
}

/**
 * A generated module, because the API routes need the POI lists inside the
 * bundle: reading public/ from a route handler works locally and quietly does
 * not on several hosts. Static imports are the one form every host agrees on.
 */
function writeIndex(manifest) {
  const lines = [
    '/* Generated by scripts/build-venue.mjs — do not edit by hand.',
    ' *',
    ' * Static imports of every venue\'s POI list, for the server-side routes.',
    ' * The browser does not use this: it fetches /venues/<id>.pois.json so that',
    ' * a new venue is a new file rather than a new deployment.',
    ' *',
    ` * Rebuild with: npm run venues:reindex`,
    ' */',
    '',
    "import manifest from '@/public/venues/manifest.json';",
  ];
  const varOf = (id) => `pois_${id.replace(/[^a-zA-Z0-9]/g, '_')}`;
  for (const v of manifest.venues) {
    lines.push(`import ${varOf(v.id)} from '@/public/venues/${v.id}.pois.json';`);
  }
  lines.push('');
  lines.push('export const MANIFEST = manifest;');
  lines.push('export const VENUES = manifest.venues;');
  lines.push(`export const DEFAULT_VENUE_ID = ${JSON.stringify(manifest.default)};`);
  lines.push('');
  lines.push('export const POIS_BY_VENUE = {');
  for (const v of manifest.venues) lines.push(`  ${JSON.stringify(v.id)}: ${varOf(v.id)},`);
  lines.push('};');
  lines.push('');
  lines.push('export const venueById = (id) => VENUES.find((v) => v.id === id) || null;');
  lines.push('');
  mkdirSync(path.dirname(INDEX_FILE), { recursive: true });
  writeFileSync(INDEX_FILE, lines.join('\n'));
}

export function readOverrides(id, explicit) {
  const file = explicit || path.join(OVERRIDE_DIR, `${id}.overrides.json`);
  const data = readJson(file);
  return data ? { file, data } : { file: null, data: null };
}
