/**
 * Universal Venue Builder — external dependency matrix (code registry).
 *
 * Evaluates open-source projects against capability, license, integration cost,
 * and overlap with scripts/ and lib/ in this repo. See also:
 *   docs/universal-venue-builder-dependency-matrix.md
 *
 * adopt modes:
 *   adopt   — use as primary implementation in a service
 *   wrap    — CLI/container adapter, no fork (preferred)
 *   fork    — only if upstream cannot be wrapped
 *   replace — supersedes something we built
 *   evaluate — head-to-head bake-off (e.g. Valhalla vs GraphHopper)
 *   defer   — Phase 2+; weights reserved in evidence engine
 *   reject  — conflicts with offline-first runtime constraints
 */

import { defineAdapter } from './types.mjs';

const ENTRIES = [
  // —— AI orchestration ——
  {
    id: 'langgraph',
    name: 'LangGraph',
    repo: 'langchain-ai/langgraph',
    url: 'https://github.com/langchain-ai/langgraph',
    capability: 'Stateful multi-agent workflows for venue build pipelines',
    role: 'BUILD_ORCHESTRATOR',
    stage: 'orchestration',
    license: 'MIT',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['python'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'venue-requests.mjs briefs humans; no agent graph yet',
    notes: 'Research / GIS / Vision / Validation agents as nodes. Runs off hot build path.',
  },
  {
    id: 'langchain',
    name: 'LangChain',
    repo: 'langchain-ai/langchain',
    url: 'https://github.com/langchain-ai/langchain',
    capability: 'LLM tools, retrievers, model integrations',
    role: 'LLM_TOOL_LAYER',
    stage: 'orchestration',
    license: 'MIT',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['python', 'javascript'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'venue-llm.mjs optional OpenAI-compatible chat only',
    notes: 'Under LangGraph, not as the architecture root.',
  },
  {
    id: 'playwright',
    name: 'Playwright',
    repo: 'microsoft/playwright',
    url: 'https://github.com/microsoft/playwright',
    capability: 'Browser automation for official sites, maps, accessibility pages',
    role: 'WEB_RESEARCH_AGENT',
    stage: 'research',
    license: 'Apache-2.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript', 'python'],
    docker: true,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['official_site', 'official_map'],
    integration: 'low',
    overlap: 'devDependency + test/browser.mjs; venue-official-site.mjs uses fetch+regex',
    notes: 'Extend research agent beyond regex HTML parsing. Not on rebuild hot path.',
  },

  // —— Theme park operational data ——
  {
    id: 'themeparks-cubehouse',
    name: 'cubehouse/themeparks',
    repo: 'cubehouse/themeparks',
    url: 'https://github.com/cubehouse/themeparks',
    capability: 'Unofficial park metadata, wait times, hours (legacy implementation)',
    role: 'VENUE_DATA_ADAPTER_LEGACY',
    stage: 'venue_data',
    license: 'MIT',
    adopt: 'evaluate',
    maturity: 'beta',
    maintenance: 2,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['parks_api'],
    integration: 'medium',
    overlap: 'No external ride APIs wired',
    notes: 'Study acquisition model; successor ParksAPI preferred for active maintenance.',
  },
  {
    id: 'parks-api',
    name: 'ParksAPI (themeparks successor)',
    repo: 'cubehouse/ParksAPI',
    url: 'https://github.com/cubehouse/ParksAPI',
    capability: 'Park identification, attraction inventories, hours, wait-time concepts',
    role: 'VENUE_DATA_ADAPTER',
    stage: 'venue_data',
    license: 'MIT',
    adopt: 'wrap',
    maturity: 'beta',
    maintenance: 4,
    languages: ['javascript', 'typescript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['parks_api'],
    integration: 'medium',
    overlap: 'Heights from official sites; no live ops feed in client',
    notes: 'Metadata + ops concepts into sidecar; client stays offline JSON.',
  },

  // —— OpenStreetMap ecosystem ——
  {
    id: 'osm',
    name: 'OpenStreetMap',
    repo: 'openstreetmap/openstreetmap-website',
    url: 'https://www.openstreetmap.org',
    capability: 'Base venue skeleton: paths, buildings, attractions, amenities',
    role: 'GEO_FOUNDATION',
    stage: 'geo',
    license: 'ODbL (data)',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['various'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['osm_entrance', 'osm_named_queue', 'osm_queue_name'],
    integration: 'low',
    overlap: 'Core: build-venue.mjs Overpass + osm-tags.mjs',
    notes: 'Already the geospatial foundation.',
  },
  {
    id: 'overpass-api',
    name: 'Overpass API',
    repo: 'drolbr/Overpass-API',
    url: 'https://github.com/drolbr/Overpass-API',
    capability: 'Structured OSM queries over bounding boxes',
    role: 'OSM_QUERY',
    stage: 'geo',
    license: 'AGPL-3.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['osm_entrance', 'osm_named_queue'],
    integration: 'low',
    overlap: 'Mirrors in build-venue.mjs',
    notes: 'Optional local Overpass for air-gapped builds.',
  },
  {
    id: 'osmium',
    name: 'Osmium',
    repo: 'osmcode/libosmium',
    url: 'https://github.com/osmcode/libosmium',
    capability: 'Fast OSM PBF processing, extracts, merges',
    role: 'OSM_TOOLKIT',
    stage: 'geo',
    license: 'BSD-2-Clause',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'Live Overpass queries today; no local PBF pipeline',
    notes: 'Regional extracts for offline routing graph prep.',
  },
  {
    id: 'nominatim',
    name: 'Nominatim',
    repo: 'osm-search/Nominatim',
    url: 'https://github.com/osm-search/Nominatim',
    capability: 'Place resolution for --place builds',
    role: 'GEO_PLACE_LOOKUP',
    stage: 'geo',
    license: 'GPL-2.0',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['python', 'c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'low',
    overlap: 'Public Nominatim in build-venue.mjs',
    notes: 'Self-hosted option for reproducible place resolution.',
  },

  // —— Routing engines ——
  {
    id: 'graphhopper',
    name: 'GraphHopper',
    repo: 'graphhopper/graphhopper',
    url: 'https://github.com/graphhopper/graphhopper',
    capability: 'OSM routing, isochrones, snap-to-network',
    role: 'VENUE_ROUTING_ENGINE_CANDIDATE',
    stage: 'geo',
    license: 'Apache-2.0',
    adopt: 'evaluate',
    maturity: 'production',
    maintenance: 4,
    languages: ['java'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'high',
    overlap: 'Client A* in lib/routing.js (~1.8ms); park-intelligence-review rejects server routing',
    notes: 'Theme parks need pedestrian venue graphs, not road networks. Bake-off with Valhalla.',
  },
  {
    id: 'valhalla',
    name: 'Valhalla',
    repo: 'valhalla/valhalla',
    url: 'https://github.com/valhalla/valhalla',
    capability: 'Pedestrian/multimodal routing, dynamic costing, regional tiles',
    role: 'VENUE_ROUTING_ENGINE_CANDIDATE',
    stage: 'geo',
    license: 'MIT',
    adopt: 'evaluate',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'high',
    overlap: 'Rejected for phone runtime; could assist builder path validation only',
    notes: 'Builder-side "minimize walking" QA, not phone dependency.',
  },

  // —— Map rendering & tiles ——
  {
    id: 'maplibre-gl-js',
    name: 'MapLibre GL JS',
    repo: 'maplibre/maplibre-gl-js',
    url: 'https://github.com/maplibre/maplibre-gl-js',
    capability: 'WebGL vector-tile map renderer with custom styling',
    role: 'MAP_RENDERER_OPTION',
    stage: 'runtime_map',
    license: 'BSD-2-Clause',
    adopt: 'evaluate',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript', 'typescript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'high',
    overlap: 'Custom SVG ParkMap.jsx — offline, dependency-free',
    notes: 'Future layer if vector tiles justify bundle size. Not required for MVP.',
  },
  {
    id: 'tippecanoe',
    name: 'Tippecanoe',
    repo: 'felt/tippecanoe',
    url: 'https://github.com/felt/tippecanoe',
    capability: 'GeoJSON → vector tiles with zoom-aware detail',
    role: 'TILE_PIPELINE',
    stage: 'tiles',
    license: 'BSD-2-Clause',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 4,
    languages: ['c++'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'medium',
    overlap: 'Full geometry in map.json today',
    notes: 'Venue Builder → GeoJSON → Tippecanoe → tiles → optional MapLibre.',
  },

  // —— Street imagery & SfM ——
  {
    id: 'mapillary-tools',
    name: 'Mapillary Tools',
    repo: 'mapillary/mapillary_tools',
    url: 'https://github.com/mapillary/mapillary_tools',
    capability: 'Geotagged imagery/video processing, GPX alignment',
    role: 'GROUND_IMAGERY_INGEST',
    stage: 'vision',
    license: 'BSD-2-Clause',
    adopt: 'wrap',
    maturity: 'production',
    maintenance: 3,
    languages: ['python'],
    docker: true,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['mapillary'],
    integration: 'medium',
    overlap: 'Manual aerial survey for Big Kahunas only',
    notes: 'Queue entrance candidates from street-level sequences + API metadata.',
  },
  {
    id: 'mapillary-js',
    name: 'Mapillary JS',
    repo: 'mapillary/mapillary-js',
    url: 'https://github.com/mapillary/mapillary-js',
    capability: 'Interactive street-level WebGL viewer',
    role: 'VALIDATION_UI_IMAGERY',
    stage: 'vision',
    license: 'MIT',
    adopt: 'defer',
    maturity: 'production',
    maintenance: 3,
    languages: ['javascript', 'typescript'],
    docker: false,
    gpu: false,
    offline: false,
    commercial_ok: true,
    evidence_sources: ['mapillary'],
    integration: 'medium',
    overlap: 'Human validation UI identified as high-leverage gap',
    notes: 'Pairs with validation UI for evidence review.',
  },
  {
    id: 'opensfm',
    name: 'OpenSfM',
    repo: 'mapillary/OpenSfM',
    url: 'https://github.com/mapillary/OpenSfM',
    capability: 'Structure-from-motion 3D reconstruction from photos',
    role: 'ADVANCED_GEOMETRY',
    stage: 'vision',
    license: 'BSD-2-Clause',
    adopt: 'defer',
    maturity: 'beta',
    maintenance: 3,
    languages: ['python'],
    docker: true,
    gpu: true,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['aerial', 'cv_segmentation'],
    integration: 'high',
    overlap: 'Phase 3 — not MVP',
    notes: 'Buildings, queues, stations from multi-view photos.',
  },

  // —— Computer vision ——
  {
    id: 'ultralytics-yolo',
    name: 'Ultralytics YOLO',
    repo: 'ultralytics/ultralytics',
    url: 'https://github.com/ultralytics/ultralytics',
    capability: 'Detection, tracking, segmentation for venue features',
    role: 'VISION_DETECTOR',
    stage: 'vision',
    license: 'AGPL-3.0',
    adopt: 'evaluate',
    maturity: 'production',
    maintenance: 5,
    languages: ['python'],
    docker: true,
    gpu: true,
    offline: true,
    commercial_ok: false,
    evidence_sources: ['cv_detection'],
    integration: 'high',
    overlap: 'Deferred in park-intelligence-review §19; guest_photo/video weights exist',
    notes: 'LICENSE: AGPL — commercial product needs enterprise license review before embed.',
  },
  {
    id: 'sam2',
    name: 'SAM 2',
    repo: 'facebookresearch/sam2',
    url: 'https://github.com/facebookresearch/sam2',
    capability: 'Promptable image/video segmentation → polygons',
    role: 'VISION_SEGMENTER',
    stage: 'vision',
    license: 'Apache-2.0',
    adopt: 'defer',
    maturity: 'beta',
    maintenance: 4,
    languages: ['python'],
    docker: true,
    gpu: true,
    offline: true,
    commercial_ok: true,
    evidence_sources: ['cv_segmentation'],
    integration: 'high',
    overlap: 'Same deferral as YOLO',
    notes: 'Segment queue structures for georeferenced polygons.',
  },

  // —— Already in repo (reference rows) ——
  {
    id: 'venue-evidence-engine',
    name: 'Evidence fusion (this repo)',
    repo: 'six-flags-sa',
    url: 'scripts/lib/evidence.mjs',
    capability: 'Source-weighted fusion, publish bands, dissent reporting',
    role: 'EVIDENCE_ENGINE',
    stage: 'research',
    license: 'project',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: Object.keys({
      official_map: 1,
      official_site: 1,
      osm_entrance: 1,
      osm_named_queue: 1,
      aerial: 1,
      mapillary: 1,
      parks_api: 1,
      cv_detection: 1,
      cv_segmentation: 1,
      guest_photo: 1,
      video: 1,
      traced: 1,
      geometry: 1,
    }),
    integration: 'low',
    overlap: 'Core — ahead of external proposals per park-intelligence-review',
    notes: 'Validated coordinates publish to pois.json; raw evidence stays in sidecar.',
  },
  {
    id: 'client-routing',
    name: 'Client path graph (this repo)',
    repo: 'six-flags-sa',
    url: 'lib/routing.js',
    capability: 'Offline A* on OSM path layer',
    role: 'PHONE_ROUTING',
    stage: 'geo',
    license: 'project',
    adopt: 'adopt',
    maturity: 'production',
    maintenance: 5,
    languages: ['javascript'],
    docker: false,
    gpu: false,
    offline: true,
    commercial_ok: true,
    evidence_sources: [],
    integration: 'low',
    overlap: '1.8ms/query; Valhalla rejected for runtime',
    notes: 'Keep unless vector routing proves necessary on phone.',
  },
];

export const ADAPTER_REGISTRY = ENTRIES.map((e) => defineAdapter(e));

export function getAdapter(id) {
  return ADAPTER_REGISTRY.find((a) => a.id === id) || null;
}

export function adaptersByStage(stage) {
  return ADAPTER_REGISTRY.filter((a) => a.stage === stage);
}

export function adaptersByAdopt(mode) {
  return ADAPTER_REGISTRY.filter((a) => a.adopt === mode);
}

export function registrySummary() {
  const byAdopt = {};
  const byStage = {};
  for (const a of ADAPTER_REGISTRY) {
    byAdopt[a.adopt] = (byAdopt[a.adopt] || 0) + 1;
    byStage[a.stage] = (byStage[a.stage] || 0) + 1;
  }
  return {
    total: ADAPTER_REGISTRY.length,
    byAdopt,
    byStage,
  };
}
