#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# The push itself is the part an agent cannot do. DesignSync cannot
# authenticate outside an interactive terminal — `/design-login` needs one —
# so no remote session can push this bundle, and prose in a doc is not a path.
# This is the path.
#
# Run it from the repo root:  npm run design:push
#
# It is safe to re-run: it rebuilds rather than assumes, remembers the project
# name, and every DesignSync call it walks you through overwrites by path.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

TOTAL_STAGES=5

# Everything the wizard prints about the bundle is read back out of the
# generator, never written down here. `design:plan` is the single place that
# knows what the push root contains; a wizard carrying its own copy of nine
# filenames is a wizard that is wrong the first time a page is renamed.
PLAN_JSON=""
plan_field() { node -e "
  const p = JSON.parse(process.argv[1]);
  $1
" "$PLAN_JSON"; }

banner "Push the Parkbound design system to Claude Design"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm you are on your own machine"
say "DesignSync cannot authenticate in a remote session: /design-login needs an"
say "interactive terminal, so the push has to happen from Claude Code running"
say "locally. This stage checks that, because the alternative is finding out at"
say "stage 4 with no way forward."
printf '\n'

REMOTE_MARKERS=()
[[ -n "${CLAUDE_CODE_REMOTE:-}" ]]            && REMOTE_MARKERS+=("CLAUDE_CODE_REMOTE")
[[ -n "${CLAUDE_CODE_REMOTE_SESSION_ID:-}" ]] && REMOTE_MARKERS+=("CLAUDE_CODE_REMOTE_SESSION_ID")
[[ -n "${CODESPACES:-}" ]]                    && REMOTE_MARKERS+=("CODESPACES")
[[ -n "${SSH_CONNECTION:-}" ]]                && REMOTE_MARKERS+=("SSH_CONNECTION")

if (( ${#REMOTE_MARKERS[@]} )); then
  warn "this looks like a remote session: ${REMOTE_MARKERS[*]} is set."
  say ""
  say "Stop here. Pull the branch down to your own machine, open Claude Code"
  say "there, and run: npm run design:push"
  printf '\n'
  exit 1
fi

if [[ ! -t 0 ]]; then
  warn "stdin is not a terminal, so /design-login could not prompt you either."
  say "Run this from an interactive shell: npm run design:push"
  printf '\n'
  exit 1
fi

printf '  %s✓%s no remote-session markers, and stdin is a terminal\n' "$GREEN" "$RESET"
note "checked: CLAUDE_CODE_REMOTE, CLAUDE_CODE_REMOTE_SESSION_ID, CODESPACES, SSH_CONNECTION, tty"
printf '\n'
pause "Press Enter to build the bundle."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Build a fresh bundle, and prove it is pushable"
say "You are about to push generated files, so they have to be generated NOW."
say "A bundle built before the last token change would push a design system that"
say "disagrees with the app, which is the whole failure this bundle exists to stop."
printf '\n'

if ! npm run --silent design:build; then
  warn "design:build failed. Fix that first; nothing below will help."
  exit 1
fi
printf '\n'

if ! npm run --silent design:check; then
  warn "design:check failed immediately after a build, which should be impossible."
  warn "Something is writing into docs/design/system/ by hand. Investigate before pushing."
  exit 1
fi
printf '\n'

# `plan` is the gate that the bundle satisfies DesignSync's own limits, and it
# prints the exact push list. It exits non-zero if the bundle is not pushable.
if ! node scripts/design-bundle.mjs plan; then
  warn "the bundle is not pushable. The lines above say why."
  exit 1
fi
printf '\n'

PLAN_JSON="$(node scripts/design-bundle.mjs plan --json)"
PUSH_ROOT="$(plan_field 'console.log(p.pushRoot)')"
FILE_COUNT="$(plan_field 'console.log(p.files.length)')"
CARD_COUNT="$(plan_field "console.log(p.files.filter((f) => f.projectPath.endsWith('.html')).length)")"

printf '  %s✓%s %s files ready under %s/\n' "$GREEN" "$RESET" "$FILE_COUNT" "$PUSH_ROOT"

if [[ -n "$(git status --porcelain -- "$PUSH_ROOT" 2>/dev/null)" ]]; then
  printf '\n'
  warn "$PUSH_ROOT/ has uncommitted changes after the rebuild."
  say "That is fine to push, but commit it too, or the repo and the project"
  say "will disagree about what was pushed."
fi
printf '\n'
pause "Press Enter to sign in to Claude Design."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Sign in, and pick a DESIGN SYSTEM project"
say "In this Claude Code session (not this script), run:"
printf '\n      %s/design-login%s\n\n' "$BOLD" "$RESET"
step "Complete the browser sign-in it opens."
printf '\n'
say "Then choose where the bundle lands:"
step "An existing design-system project, or a new one you create now."
printf '\n'
warn "Project type is fixed at creation and cannot be changed afterwards."
say "A regular Design project can never become a design system. If the project"
say "you have in mind is a regular one, create a NEW design-system project"
say "instead of trying to convert it — there is no conversion."
printf '\n'
note "The wizard cannot verify this for you: DesignSync is a tool inside Claude"
note "Code, not something this shell can call. You are the check here."
printf '\n'

ask DESIGN_PROJECT "Name (or id) of the design-system project you are pushing to:"
if [[ -z "$DESIGN_PROJECT" ]]; then
  warn "no project named; re-run when you have created or chosen one."
  exit 1
fi
write_env DESIGN_PROJECT "$DESIGN_PROJECT"
note "remembered, so a re-run offers it back as the default"
printf '\n'

if ! confirm "Signed in, and '$DESIGN_PROJECT' is a DESIGN SYSTEM project?"; then
  say "Stop here and sort that out; re-run when it is true. Nothing has been pushed."
  exit 1
fi
printf '\n'
pause "Press Enter for the push itself."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Push the bundle"
say "Three DesignSync calls, in this order, in your Claude Code session."
say "Ask Claude to run them, or drive them yourself."
printf '\n'

printf '  %s1. list_files%s — see what the project already has, so you know what\n' "$BOLD" "$RESET"
say "     you are replacing. Safe, and safe to repeat."
printf '\n'
printf '  %s2. finalize_plan%s — declare the writes. The write list is exactly these\n' "$BOLD" "$RESET"
printf '     %s project paths:\n' "$FILE_COUNT"
printf '\n'
plan_field "for (const f of p.files) console.log('       ' + f.projectPath)"
printf '\n'
printf '  %s3. write_files%s — each entry carries a localPath and a mimeType. Paths\n' "$BOLD" "$RESET"
say "     are relative to the repo root, so run it from there:"
printf '\n'
printf '       %srepo root:%s %s\n' "$DIM" "$RESET" "$(pwd)"
printf '\n'
plan_field "
  const w = Math.max(...p.files.map((f) => f.localPath.length));
  for (const f of p.files) {
    console.log('       ' + f.projectPath.padEnd(Math.max(...p.files.map((x) => x.projectPath.length))) +
      '  ←  ' + f.localPath.padEnd(w) + '  ' + f.mimeType);
  }
"
printf '\n'
warn "The woff2 files are not optional decoration."
say "They ARE the design system's typeface. Push them with the pages or the"
say "project renders in a system fallback and misrepresents the app's type."
printf '\n'
note "Re-running this push later is safe: write_files overwrites by path, and"
note "every path above is derived from the bundle, so it is stable across runs."
printf '\n'
pause "Press Enter once write_files has reported success."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify it landed — do not assume"
say "This round trip has never been exercised from a remote session, because it"
say "cannot be. Yours may be the first real push. Check it rather than trust it."
printf '\n'

printf '  %sA. The Design System pane shows %s cards, in these groups:%s\n' "$BOLD" "$CARD_COUNT" "$RESET"
printf '\n'
node -e "
  const m = JSON.parse(require('fs').readFileSync('$PUSH_ROOT/_ds_manifest.json', 'utf8'));
  const byGroup = new Map();
  for (const c of m.cards) byGroup.set(c.group, [...(byGroup.get(c.group) || []), c.title]);
  for (const [g, titles] of byGroup) {
    console.log('       ' + g + ' (' + titles.length + '): ' + titles.join(', '));
  }
"
printf '\n'
note "A missing card almost always means its @dsCard comment did not survive as"
note "the first line of the file. Re-run npm run design:check, then re-push."
printf '\n'

printf '  %sB. The type is really Plus Jakarta Sans, not a fallback.%s\n' "$BOLD" "$RESET"
say "     Open any pushed page, then in the browser devtools console run:"
printf '\n'
printf "       %sdocument.fonts.check(\"800 32px 'Plus Jakarta Sans'\")%s\n" "$BOLD" "$RESET"
printf '\n'
say "     It must print true AFTER the page has painted a heading. If it prints"
say "     false, the woff2 did not arrive at:"
printf '\n'
plan_field "for (const f of p.files.filter((f) => f.mimeType === 'font/woff2')) console.log('       ' + f.projectPath)"
printf '\n'
note "Eyeballing the type does not settle this. Plus Jakarta Sans and the"
note "fallback stack are similar enough at a glance that the last bundle shipped"
note "broken font paths for its whole life without anyone noticing."
printf '\n'

if confirm "Both checks pass?"; then
  printf '  %s✓%s the project is carrying a fresh, self-contained bundle\n' "$GREEN" "$RESET"
else
  SKIPPED+=("verification did not pass — re-check the two items in stage 5 before trusting the project")
fi

finish
